version: '3'
services:
  queue:
    image: 'rabbitmq:latest'

  database:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    build: 'backend/.'
    depends_on:
      - queue
      - database
